// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class incluirNome_TipoSubscricao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(incluirNome_TipoSubscricao));
        
        string IMigrationMetadata.Id
        {
            get { return "201912170835518_incluirNome_TipoSubscricao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
